name: contact_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  qr_flutter: ^4.0.0
  url_launcher: ^6.0.0
  image_picker: ^0.8.4+4
  mongo_dart: ^0.10.1
  
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
